// REAL AI Intelligence: queries the ai_insights table. The previous version
// shipped a hardcoded array of 10 strings — that's gone. Insights are now
// generated by edge functions (compliance-watcher etc.) and persisted with
// citations to source rows.

import { useEffect, useMemo, useState } from 'react';
import { Brain, ChevronRight, X, Filter, Loader2 } from 'lucide-react';
import { supabase, supabaseConfigured, invokeFn } from '../lib/supabase';
import type { AIInsight } from '@stigg/shared';

export function AIIntelligence() {
  const [rows, setRows] = useState<AIInsight[]>([]);
  const [loading, setLoading] = useState(true);
  const [scanning, setScanning] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [surface, setSurface] = useState<string>('all');

  async function load() {
    if (!supabaseConfigured) { setError('Supabase not configured.'); setLoading(false); return; }
    const { data, error } = await supabase
      .from('ai_insights')
      .select('*')
      .is('dismissed_at', null)
      .order('severity', { ascending: false })
      .order('created_at', { ascending: false })
      .limit(100);
    if (error) setError(error.message);
    setRows((data ?? []) as AIInsight[]);
    setLoading(false);
  }
  useEffect(() => { load(); }, []);

  const surfaces = useMemo(() => Array.from(new Set(rows.map((r) => r.surface))), [rows]);
  const filtered = surface === 'all' ? rows : rows.filter((r) => r.surface === surface);

  async function runScan() {
    setScanning(true); setError(null);
    try {
      await invokeFn('compliance-watcher', {});
      await load();
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e));
    } finally {
      setScanning(false);
    }
  }

  async function dismiss(id: string) {
    await supabase.from('ai_insights').update({ dismissed_at: new Date().toISOString() }).eq('id', id);
    setRows((prev) => prev.filter((r) => r.id !== id));
  }

  return (
    <div className="space-y-6">
      <div className="flex items-end justify-between">
        <div>
          <h1 className="text-3xl font-bold flex items-center gap-2">
            <Brain className="text-blue-400" /> AI Intelligence
          </h1>
          <p className="text-slate-400 mt-1">
            Insights generated by Stigg's agents — every one cites the source rows that drove it.
          </p>
        </div>
        <button className="btn-primary inline-flex items-center gap-2" onClick={runScan} disabled={scanning || !supabaseConfigured}>
          {scanning ? <><Loader2 size={16} className="animate-spin" /> Scanning…</> : 'Run compliance scan'}
        </button>
      </div>

      {error && (
        <div className="card border-red-500/30 bg-red-500/10 text-red-200">
          <p className="font-medium">Cannot load insights</p>
          <p className="text-sm mt-1">{error}</p>
        </div>
      )}

      <div className="card flex flex-wrap items-center gap-2">
        <Filter size={14} className="text-slate-400" />
        <button
          onClick={() => setSurface('all')}
          className={`text-xs px-3 py-1 rounded ${surface === 'all' ? 'bg-blue-600 text-white' : 'bg-slate-800 text-slate-300 hover:bg-slate-700'}`}
        >
          All
        </button>
        {surfaces.map((s) => (
          <button
            key={s}
            onClick={() => setSurface(s)}
            className={`text-xs px-3 py-1 rounded ${surface === s ? 'bg-blue-600 text-white' : 'bg-slate-800 text-slate-300 hover:bg-slate-700'}`}
          >
            {s}
          </button>
        ))}
      </div>

      {loading ? (
        <div className="text-slate-500 text-sm">Loading…</div>
      ) : filtered.length === 0 ? (
        <div className="card text-center">
          <Brain className="mx-auto opacity-40 mb-3" size={32} />
          <p className="text-slate-300">No active insights.</p>
          <p className="text-sm text-slate-500 mt-1">
            Run a compliance scan to surface license expiries, training gaps, and PIPEDA breach-register lags.
          </p>
        </div>
      ) : (
        <div className="space-y-3">
          {filtered.map((i) => (
            <div key={i.id} className="card">
              <div className="flex items-start gap-3">
                <span className={`text-[10px] px-2 py-0.5 rounded h-fit ${
                  i.severity === 'critical' ? 'badge-critical' :
                  i.severity === 'high'     ? 'badge-high'     :
                  i.severity === 'medium'   ? 'badge-medium'   : 'badge-low'
                }`}>{i.severity}</span>
                <div className="flex-1 min-w-0">
                  <h3 className="font-medium">{i.title}</h3>
                  <p className="text-sm text-slate-400 mt-1">{i.description}</p>
                  {i.recommended_action && (
                    <p className="text-sm text-blue-300 mt-2 inline-flex items-center gap-1">
                      <ChevronRight size={14} /> {i.recommended_action}
                    </p>
                  )}
                  {i.citations.length > 0 && (
                    <div className="mt-3 flex flex-wrap gap-2">
                      {i.citations.map((c, idx) => (
                        <span key={idx} className="text-[10px] px-2 py-0.5 rounded bg-slate-800 text-slate-400 border border-slate-700">
                          {c.table}:{c.id.slice(0, 6)}{c.note ? ` (${c.note})` : ''}
                        </span>
                      ))}
                    </div>
                  )}
                  <div className="mt-2 text-xs text-slate-500">
                    Confidence {Math.round((i.confidence ?? 0) * 100)}% · {i.surface} · {new Date(i.created_at).toLocaleString()}
                  </div>
                </div>
                <button
                  onClick={() => dismiss(i.id)}
                  className="text-slate-500 hover:text-red-400 p-1"
                  title="Dismiss"
                >
                  <X size={14} />
                </button>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
