#!/usr/bin/env tsx
/**
 * Seed the Northview Residential REIT seasonal contract end-to-end.
 *
 * Idempotent — safe to re-run. Every upsert is keyed by a stable identifier
 * (client.account_number, site.name, contract.contract_number, etc.).
 *
 * Loads:
 *   • Client                              Northview Residential REIT
 *   • 7 sites                             Parkview I/II, 6/4 Nixon, 16/15 Saunderson, MacDonald
 *   • Contract                            NV-2026-0001 with seasonal pricing
 *   • contract_sites links                Marks MacDonald as is_optional
 *   • Tour routes A/B + 6 checkpoints     Each site
 *   • Post orders                         Markdown body per site
 *   • Arming schedule                     "Northview after-hours patrol"
 *   • Linkage rule                        Notify on missed-tour at any Northview site
 *   • Dawn Collier portal user
 *   • 60 days of shifts                   Generated by @stigg/scheduling
 *
 * Usage:
 *   SUPABASE_URL=... SUPABASE_SERVICE_ROLE_KEY=... \
 *     npm run seed:northview -- --org=<org_uuid> [--dawn-password=<temp>] [--days=60]
 */

import { createClient } from '@supabase/supabase-js';
// Direct relative imports — tsx resolves .ts via the .js extension convention.
import { generateSchedule } from '../packages/scheduling/src/seasonal.ts';
import type { ScheduleSite, SeasonalConfig } from '../packages/scheduling/src/types.ts';

// ─── CLI args + env ────────────────────────────────────────────────────────

const args = Object.fromEntries(process.argv.slice(2).map((a) => {
  const m = a.match(/^--([^=]+)=(.*)$/); return m ? [m[1], m[2]] : [a, true];
}));

const orgId = args.org as string;
const days = parseInt((args.days as string) ?? '60', 10);
const dawnEmail = (args['dawn-email'] as string) ?? 'dawn.collier@northviewreit.example';
const dawnPassword = (args['dawn-password'] as string) ?? '';

if (!orgId) {
  console.error('usage: tsx scripts/seed-northview.ts --org=<org_uuid> [--dawn-password=<temp>] [--days=60]');
  process.exit(2);
}
const url = process.env.SUPABASE_URL!;
const key = process.env.SUPABASE_SERVICE_ROLE_KEY!;
if (!url || !key) { console.error('SUPABASE_URL + SUPABASE_SERVICE_ROLE_KEY required'); process.exit(2); }
const sb = createClient(url, key, { auth: { persistSession: false } });

// ─── Source-of-truth contract data (lifted from the signed Northview MSA) ───

const SITES = [
  { name: 'Parkview I Apartments',   address: '9501 Manning Avenue',   city: 'Fort McMurray', region: 'AB', postal: 'T9H 0B1', lat: 56.7263, lng: -111.3790, suites: 80, optional: false },
  { name: 'Parkview II Apartments',  address: '9501A Manning Avenue',  city: 'Fort McMurray', region: 'AB', postal: 'T9H 0B1', lat: 56.7264, lng: -111.3791, suites: 55, optional: false },
  { name: '6 Nixon',                 address: '6 Nixon Street',        city: 'Fort McMurray', region: 'AB', postal: 'T9H 0B5', lat: 56.7261, lng: -111.3801, suites: 71, optional: false },
  { name: '4 Nixon',                 address: '4 Nixon Street',        city: 'Fort McMurray', region: 'AB', postal: 'T9H 0B5', lat: 56.7260, lng: -111.3805, suites: 44, optional: false },
  { name: '16 Saunderson',           address: '16 Saunderson Avenue',  city: 'Fort McMurray', region: 'AB', postal: 'T9H 0B7', lat: 56.7280, lng: -111.3792, suites: 59, optional: false },
  { name: '15 Saunderson',           address: '15 Saunderson Avenue',  city: 'Fort McMurray', region: 'AB', postal: 'T9H 0B7', lat: 56.7281, lng: -111.3795, suites: 55, optional: false },
  { name: 'MacDonald Place',         address: '10126 MacDonald Avenue',city: 'Fort McMurray', region: 'AB', postal: 'T9H 0E1', lat: 56.7258, lng: -111.3782, suites: 51, optional: true  },
] as const;

const CHECKPOINTS = [
  { ordinal: 1, label: 'Front entrance',  scan_method: 'qr' },
  { ordinal: 2, label: 'Lobby / mail',    scan_method: 'qr' },
  { ordinal: 3, label: 'Parking area',    scan_method: 'qr' },
  { ordinal: 4, label: 'Stairwell A',     scan_method: 'nfc' },
  { ordinal: 5, label: 'Laundry room',    scan_method: 'nfc' },
  { ordinal: 6, label: 'Rear / perimeter',scan_method: 'qr' },
] as const;

const POST_ORDER_TEMPLATE = (site: { name: string; address: string; suites: number }) => `# Post Order — ${site.name}

**Address.** ${site.address}, Fort McMurray, AB
**Suite count.** ${site.suites}
**Client.** Northview Residential REIT
**Coverage.** Seasonal mobile patrol per Northview MSA NV-2026-0001
**Effective.** ${new Date().toISOString().slice(0, 10)} — month-to-month with 30 days' notice

## On arrival
1. Park in a marked stall, hazards on if engine running. Maintain marked-vehicle visibility.
2. Walk perimeter clockwise: front entrance → lobby/mail → parking → stairwells → laundry → rear/perimeter.
3. Scan each checkpoint NFC/QR tag in order. Photograph anything abnormal.

## What to look for
- Unsecured doors (front, rear, mail room, mechanical, laundry).
- Loitering, intoxication-related disturbance, unauthorized access by non-residents.
- Pry-bar marks, recent door damage, tampering with cameras or locks.
- Vandalism (graffiti, broken glass, dumped items).
- Weather hazards (ice, fallen branches, blocked emergency egress).

## Reporting & escalation
- **Same-shift incident reports** for any of the above. Use Incident Copilot — speak the narration; the Copilot structures it.
- **Immediate escalation** to dispatch for: active break-in, fire/medical, weapons, life-safety.
- Notify designated Northview contact (Dawn Collier or after-hours delegate) for priority events without delay.
- Daily activity report submitted by 09:00 the following morning.

## Authority & boundaries
- You are present under the property owner's authority. Verbal intervention + de-escalation first.
- Trespass enforcement only where the lease/posting permits and only when safe.
- No physical use of force except in defence of self/others.
- Do not enter individual suites unless explicitly summoned by Northview management for a documented welfare check.

## Hours / pattern
- Summer (May–Oct): one Wave-1 visit per night. MacDonald Place: alternating nights.
- Winter (Nov–Apr): two visits per night (Wave 1 evening, Wave 2 early morning). MacDonald Place: nightly.
- Times randomized within their windows. Supervisors may flex ±15 min for incidents, weather, or management requests.

## KPIs
This site contributes to the contract-level KPI buckets: Asset Protection, Patrol Delivery, Incident Response, Hotspot Trends, Maintenance Impact. Patrol completion < 100% requires written explanation in the daily activity report.
`;

const SEASONAL_PRICING = {
  kind: 'seasonal' as const,
  default_currency: 'CAD',
  schedule: [
    { label: 'summer', months: [5,6,7,8,9,10], monthly_cad: 9900,  components: [
      { label: 'Core portfolio',     monthly_cad: 8950 },
      { label: 'MacDonald add-on',   monthly_cad: 950 },
    ]},
    { label: 'winter', months: [11,12,1,2,3,4], monthly_cad: 14150, components: [
      { label: 'Core portfolio',     monthly_cad: 12500 },
      { label: 'MacDonald add-on',   monthly_cad: 1650 },
    ]},
  ],
};

const KPI_TARGETS = {
  patrol_completion_pct_min: 100,
  priority_escalation_max_minutes: 0,         // "immediate"
  incident_report_within_shift: true,
  monthly_review: true,
};

// ─── Helpers ────────────────────────────────────────────────────────────────

async function upsertOnce<T extends Record<string, any>>(
  table: string, match: Record<string, any>, payload: Record<string, any>,
): Promise<T> {
  let q = sb.from(table).select('*');
  for (const [k, v] of Object.entries(match)) q = q.eq(k, v as any);
  const { data: existing } = await q.maybeSingle();
  if (existing) {
    const { data, error } = await sb.from(table).update(payload).eq('id', existing.id).select('*').single();
    if (error) throw error;
    return data as T;
  }
  const { data, error } = await sb.from(table).insert({ ...match, ...payload }).select('*').single();
  if (error) throw error;
  return data as T;
}

async function ensure<T extends Record<string, any>>(
  table: string, match: Record<string, any>, payload: Record<string, any>,
): Promise<T> { return upsertOnce<T>(table, match, payload); }

const wkt = (lng: number, lat: number) => `POINT(${lng} ${lat})`;

// ─── Main ───────────────────────────────────────────────────────────────────

async function main() {
  console.log('▶ Seeding Northview seasonal contract into org', orgId);

  // 1) Client.
  const client = await ensure<{ id: string }>('clients',
    { org_id: orgId, account_number: 'NV-NORTHVIEW' },
    {
      name: 'Northview Residential REIT',
      legal_name: 'Northview Canadian High Yield Residential Fund',
      industry: 'real_estate',
      tier: 'Premium',
      status: 'active',
      service_lines: ['guarding'],
      portal_enabled: true,
      primary_contact: { name: 'Dawn Collier', title: 'Regional Manager', email: dawnEmail },
      tags: ['residential', 'fort-mcmurray', 'reit'],
    },
  );
  console.log(`✓ client ${client.id}`);

  // 2) Sites + post orders + tour routes + checkpoints.
  const siteIdByName = new Map<string, string>();
  for (const spec of SITES) {
    const site = await ensure<{ id: string }>(
      'sites',
      { org_id: orgId, name: spec.name, client_id: client.id },
      {
        address: { street: spec.address, city: spec.city, province: spec.region, postal: spec.postal },
        city: spec.city, region: spec.region, postal_code: spec.postal,
        geo: wkt(spec.lng, spec.lat),
        geofence_radius_m: 120,
        site_type: 'residential',
        remote: false,
        hazards: [],
        service_lines: ['guarding'],
        is_active: true,
        post_order_template: POST_ORDER_TEMPLATE(spec),
        metadata: { suites: spec.suites, optional: spec.optional },
      },
    );
    siteIdByName.set(spec.name, site.id);

    // Post-order row (versioned).
    const { data: existingPost } = await sb.from('post_orders').select('id').eq('site_id', site.id).eq('is_current', true).maybeSingle();
    if (!existingPost) {
      await sb.from('post_orders').insert({
        org_id: orgId, site_id: site.id, version: 1,
        body_md: POST_ORDER_TEMPLATE(spec),
        is_current: true,
      });
    }

    // Two tour routes per site (A and B).
    for (const flow of ['A', 'B'] as const) {
      const route = await ensure<{ id: string }>(
        'tour_routes',
        { org_id: orgId, site_id: site.id, name: `Route ${flow}` },
        { expected_duration_min: 25, is_active: true },
      );
      // Idempotent checkpoints.
      for (const cp of CHECKPOINTS) {
        const tokenSeed = `${site.id}:${flow}:${cp.ordinal}`;
        await upsertOnce('tour_checkpoints',
          { org_id: orgId, route_id: route.id, ordinal: cp.ordinal },
          { label: cp.label, scan_method: cp.scan_method, scan_token: tokenSeed },
        );
      }
    }
  }
  console.log(`✓ ${SITES.length} sites + post orders + ${SITES.length * 2} routes + ${SITES.length * 2 * CHECKPOINTS.length} checkpoints`);

  // 3) Arming schedule — Northview after-hours patrol windows.
  const arming = await ensure<{ id: string }>(
    'arming_schedules',
    { org_id: orgId, name: 'Northview after-hours patrol' },
    {
      spec: {
        timezone: 'America/Edmonton',
        windows: [
          { days: [1,2,3,4,5,6,7], start: '19:30', end: '23:30' },   // Wave 1
          { days: [1,2,3,4,5,6,7], start: '00:30', end: '03:30' },   // Wave 2 (winter)
        ],
      },
      is_active: true,
    },
  );

  // 4) Linkage rule: missed tour at any Northview site → notify management.
  // Org-wide listener on `tour_miss` events; uses the arming window so we
  // don't auto-notify outside the patrol window.
  await upsertOnce('linkage_rules',
    { org_id: orgId, scope_type: 'org', priority: 50 },
    {
      event_types: ['tour_miss'],
      arming_schedule_id: arming.id,
      actions: [{ kind: 'notify_email', params: { to: dawnEmail, subject: 'Northview — patrol miss notification' } }],
      is_active: true,
    },
  );

  // 5) Contract.
  const today = new Date().toISOString().slice(0, 10);
  const contract = await ensure<{ id: string }>(
    'contracts',
    { org_id: orgId, contract_number: 'NV-2026-0001' },
    {
      client_id: client.id,
      service_lines: ['guarding'],
      start_date: today,
      end_date: null,
      monthly_value_cad: 14150,                                     // peak winter rate
      bill_terms: 'Monthly in arrears, GST 5% extra, net 30. Month-to-month with 30 days written notice.',
      pricing_schedule: SEASONAL_PRICING,
      kpi_targets: KPI_TARGETS,
      status: 'active',
      signed_at: new Date().toISOString(),
    },
  );

  // 6) contract_sites links.
  for (const [name, site_id] of siteIdByName.entries()) {
    const spec = SITES.find((s) => s.name === name)!;
    await upsertOnce('contract_sites',
      { contract_id: contract.id, site_id },
      { org_id: orgId, is_optional: spec.optional, added_at: today },
    );
  }
  console.log(`✓ contract ${contract.id} with seasonal pricing`);

  // 7) Dawn Collier — client portal user.
  if (dawnPassword) {
    const { data: existing } = await sb.auth.admin.listUsers();
    const existingUser = existing.users.find((u) => u.email?.toLowerCase() === dawnEmail.toLowerCase());
    let authUserId: string;
    if (existingUser) {
      authUserId = existingUser.id;
      await sb.auth.admin.updateUserById(authUserId, { password: dawnPassword });
    } else {
      const { data, error } = await sb.auth.admin.createUser({ email: dawnEmail, password: dawnPassword, email_confirm: true });
      if (error) throw error;
      authUserId = data.user.id;
    }
    await upsertOnce('user_profiles',
      { auth_user_id: authUserId, org_id: orgId },
      { email: dawnEmail, full_name: 'Dawn Collier', role: 'client', client_id: client.id, is_active: true },
    );
    console.log(`✓ portal user ${dawnEmail} (role=client, scoped to Northview)`);
  } else {
    console.log(`↺ skipping Dawn Collier auth user — pass --dawn-password=<temp> to provision`);
  }

  // 8) Generate and insert the next ${days} days of shifts.
  const sites: ScheduleSite[] = SITES.map((s) => ({
    site_id: siteIdByName.get(s.name)!,
    is_optional: s.optional,
  }));
  const cfg: SeasonalConfig = {
    summer_months: [5,6,7,8,9,10],
    winter_months: [11,12,1,2,3,4],
    summer_visits_per_night: 1,
    winter_visits_per_night: 2,
    wave_1_start: '19:30',
    wave_1_end:   '23:30',
    wave_2_start: '00:30',
    wave_2_end:   '03:30',
    visit_duration_min: 25,
    flows: [
      { id: 'A', site_order: SITES.map((s) => siteIdByName.get(s.name)!) },
      { id: 'B', site_order: [
        siteIdByName.get('Parkview I Apartments')!,
        siteIdByName.get('6 Nixon')!,
        siteIdByName.get('16 Saunderson')!,
        siteIdByName.get('Parkview II Apartments')!,
        siteIdByName.get('4 Nixon')!,
        siteIdByName.get('15 Saunderson')!,
        siteIdByName.get('MacDonald Place')!,
      ]},
    ],
    timezone: 'America/Edmonton',
    bill_rate_cad_hr: 39.40,
    pay_rate_cad_hr:  19.50,
    summer_optional_pattern: 'every_other_day',
  };

  const start = new Date();
  const end = new Date(start.getTime() + days * 86_400_000);
  const startISO = start.toISOString().slice(0, 10);
  const endISO = end.toISOString().slice(0, 10);
  const shifts = generateSchedule({
    config: cfg, sites,
    start_date: startISO,
    end_date: endISO,
    seed: `${contract.id}:${startISO}`,
  });

  // 8a) Insert demand rows (guard_id NULL — the Schedule Agent assigns later).
  // Idempotency: we never insert a duplicate (site_id, scheduled_start) tuple.
  let inserted = 0, skipped = 0;
  for (const s of shifts) {
    const { data: existing } = await sb.from('shifts').select('id')
      .eq('org_id', orgId).eq('site_id', s.site_id).eq('scheduled_start', s.scheduled_start)
      .maybeSingle();
    if (existing) { skipped++; continue; }
    const { error } = await sb.from('shifts').insert({
      org_id: orgId, site_id: s.site_id, guard_id: null,
      scheduled_start: s.scheduled_start, scheduled_end: s.scheduled_end,
      shift_type: s.shift_type, status: 'scheduled',
      bill_rate: s.bill_rate ?? null, pay_rate: s.pay_rate ?? null,
      generated_by_ai: true,
      notes: `Northview ${s.flow} · wave ${s.wave}`,
    });
    if (error) {
      console.warn(`  ! shift insert failed at ${s.scheduled_start}: ${error.message}`);
    } else {
      inserted++;
    }
  }
  console.log(`✓ shifts: ${inserted} inserted, ${skipped} already present (${shifts.length} total demand rows)`);

  console.log('\n▶ Northview seed complete.');
  console.log('   Contract: NV-2026-0001');
  console.log(`   Client portal login: ${dawnEmail}${dawnPassword ? '' : ' (set --dawn-password to provision)'}`);
  console.log(`   Shifts seeded: ${days} days starting ${startISO}`);
  console.log('   Next steps:');
  console.log('     • Open Console → Contracts → NV-2026-0001 to see KPI dashboard');
  console.log('     • Open Console → Cameras to add NVRs if any');
  console.log('     • Open Console → Scheduling → Generate to assign guards to demand');
}

main().catch((e) => { console.error(e); process.exit(1); });
