// POST /functions/v1/compliance-watcher
// Daily-scheduled function (or on-demand). Pulls org state, runs the
// deterministic compliance package server-side (vendored as inline rules
// here to avoid esm import friction), then asks the model to triage and
// prose-ify each finding before inserting into ai_insights.

import { authenticate } from '../_shared/auth.ts';
import { json, preflight } from '../_shared/cors.ts';
import { runLoop, type ToolDef } from '../_shared/agent-loop.ts';

const SYSTEM_STATIC = `You are Compliance Co-pilot. You receive a list of pre-validated compliance Findings (deterministic, generated by code — never invent additions). Your job:

  1. For each finding, write a 1–3 sentence human-readable description with the regulatory anchor.
  2. Assign or confirm severity (low/medium/high/critical).
  3. Recommend one concrete action.
  4. Cite the source row table+id.

Constraints:
  • Do not invent new findings. Only describe what is in the payload.
  • Strip personal identifiers beyond name + license number.
  • Empty payload → empty insights array (do not pad).`;

interface Finding {
  rule_id: string;
  severity: 'low' | 'medium' | 'high' | 'critical';
  scope_type: 'guard' | 'site' | 'client' | 'contract' | 'org';
  scope_id?: string;
  title: string;
  description: string;
  regulatory_anchor: string;
  recommended_action: string;
  due_by?: string;
  citations: Array<{ table: string; id: string; note?: string }>;
}

const DAY = 86_400_000;

function daysUntil(iso: string | null, now: Date): number | null {
  if (!iso) return null;
  const t = Date.parse(iso);
  if (Number.isNaN(t)) return null;
  return Math.ceil((t - now.getTime()) / DAY);
}

function ssiaFindings(guards: any[], now: Date): Finding[] {
  const out: Finding[] = [];
  for (const g of guards) {
    if (g.status !== 'active') continue;
    const d = daysUntil(g.ssia_license_expiry, now);
    if (d === null) {
      out.push({
        rule_id: 'AB-SSIA-001', severity: 'high', scope_type: 'guard', scope_id: g.id,
        title: `Missing SSIA license — ${g.first_name} ${g.last_name}`,
        description: 'Active guard has no Alberta SSIA license recorded.',
        regulatory_anchor: 'AB SSIA Part 2',
        recommended_action: 'Pull from rotation until valid license recorded.',
        citations: [{ table: 'guards', id: g.id }],
      });
      continue;
    }
    if (d < 0) {
      out.push({
        rule_id: 'AB-SSIA-002', severity: 'critical', scope_type: 'guard', scope_id: g.id,
        title: `EXPIRED SSIA license — ${g.first_name} ${g.last_name}`,
        description: `License expired ${-d} day(s) ago.`,
        regulatory_anchor: 'AB SSIA Part 2',
        recommended_action: 'Block scheduling immediately; initiate renewal.',
        citations: [{ table: 'guards', id: g.id }],
      });
    } else if (d <= 30) {
      out.push({
        rule_id: 'AB-SSIA-003', severity: d <= 14 ? 'high' : 'medium', scope_type: 'guard', scope_id: g.id,
        title: `SSIA license expires in ${d} days — ${g.first_name} ${g.last_name}`,
        description: `Renewal lead time at AB Justice is 4–6 weeks.`,
        regulatory_anchor: 'AB SSIA Part 2',
        recommended_action: 'Open renewal task; pre-book replacement coverage post-expiry.',
        due_by: g.ssia_license_expiry ?? undefined,
        citations: [{ table: 'guards', id: g.id }],
      });
    }
  }
  return out;
}

Deno.serve(async (req) => {
  const pre = preflight(req); if (pre) return pre;
  if (req.method !== 'POST') return json(req, 405, { error: 'method not allowed' });

  const ctx = await authenticate(req);
  if (ctx instanceof Response) return ctx;

  if (!['owner', 'admin', 'manager'].includes(ctx.role)) {
    return json(req, 403, { error: 'compliance scan requires manager+ role' });
  }

  const now = new Date();
  const [{ data: guards }, { data: sites }, { data: breaches }] = await Promise.all([
    ctx.user.from('guards').select('id, first_name, last_name, status, ssia_license_expiry, first_aid_expiry'),
    ctx.user.from('sites').select('id, name, site_type, remote, hazards'),
    ctx.user.from('privacy_breach_register').select('id, detected_at, notification_sent, opc_reported, records_affected'),
  ]);

  const findings: Finding[] = [];
  findings.push(...ssiaFindings(guards ?? [], now));
  // First-aid + remote-site rules elided here for brevity — same shape as ssiaFindings.

  // Defensive cap so we never blast the model with thousands of findings.
  const capped = findings.slice(0, 100);

  let inserted = 0;

  const tools: ToolDef[] = [
    {
      name: 'emit_insights',
      description: 'Persist structured insights for the AI Intelligence dashboard.',
      input_schema: {
        type: 'object',
        properties: {
          insights: {
            type: 'array',
            items: {
              type: 'object',
              properties: {
                surface: { type: 'string' },
                scope_type: { type: 'string' },
                scope_id: { type: 'string' },
                title: { type: 'string' },
                description: { type: 'string' },
                confidence: { type: 'number' },
                severity: { type: 'string', enum: ['low','medium','high','critical'] },
                recommended_action: { type: 'string' },
                citations: { type: 'array', items: { type: 'object', additionalProperties: true } },
              },
              required: ['surface', 'scope_type', 'title', 'description', 'confidence', 'severity', 'recommended_action', 'citations'],
              additionalProperties: false,
            },
          },
        },
        required: ['insights'],
        additionalProperties: false,
      },
      handler: async (input) => {
        const i = input as { insights: any[] };
        if (i.insights.length === 0) return { count: 0 };
        const rows = i.insights.map((x: any) => ({
          org_id: ctx.org_id,
          surface: x.surface ?? 'compliance',
          scope_type: x.scope_type,
          scope_id: x.scope_id ?? null,
          title: x.title,
          description: x.description,
          confidence: x.confidence,
          severity: x.severity,
          recommended_action: x.recommended_action,
          citations: x.citations ?? [],
        }));
        const { error } = await ctx.service.from('ai_insights').insert(rows);
        if (error) throw new Error(error.message);
        inserted = rows.length;
        return { count: rows.length };
      },
    },
  ];

  if (capped.length === 0) {
    // Skip the model entirely when there's nothing to triage.
    return json(req, 200, { findings: 0, inserted: 0, skipped: true });
  }

  try {
    const result = await runLoop({
      modelRole: 'agent',
      systemStatic: SYSTEM_STATIC,
      systemDynamic: `Findings payload (${capped.length}):\n${JSON.stringify(capped)}`,
      userMessage: 'Triage and emit insights for these findings. Do not invent any new ones.',
      tools,
      temperature: 0.1,
      maxIterations: 3,
    });

    await ctx.service.from('ai_sessions').insert({
      org_id: ctx.org_id, user_id: ctx.user_id,
      surface: 'compliance_watcher', model: result.modelUsed, status: 'completed',
      total_input_tokens: result.usageTotals.input,
      total_output_tokens: result.usageTotals.output,
      cache_read_tokens: result.usageTotals.cacheRead,
      cache_write_tokens: result.usageTotals.cacheWrite,
    });

    return json(req, 200, { findings: capped.length, inserted });
  } catch (err) {
    return json(req, 500, { error: err instanceof Error ? err.message : String(err) });
  }
});
